name: node-cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            set -e

            cd /var/www/nodejs

            git fetch origin main

            git reset --hard origin/main

            docker compose down

            docker compose up -d --build

